name: 游닄 Melhoria na Documenta칞칚o
description: Reporte um erro, omiss칚o ou parte confusa na documenta칞칚o do projeto.
title: "[DOCS]: "
labels: ["documenta칞칚o", "boa primeira contribui칞칚o"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por ajudar a melhorar nossa documenta칞칚o! Docs claras s칚o essenciais.
  - type: input
    id: url
    attributes:
      label: URL ou Arquivo da Documenta칞칚o
      description: Por favor, forne칞a o link exato (URL) ou nome do arquivo onde o problema existe.
      placeholder: Ex: /docs/instalacao.md ou README.md
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Descreva o problema na documenta칞칚o
      description: Explique o que est치 errado, faltando, confuso ou precisa de atualiza칞칚o.
      placeholder: O bloco de c칩digo de exemplo est치 quebrado, ou a se칞칚o X est치 desatualizada.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Sugest칚o de Corre칞칚o ou Conte칰do
      description: (Opcional) Se voc칡 souber como corrigir, forne칞a o texto ou c칩digo corrigido.
      placeholder: Mudar "Clique em Salvar" para "Clique em Aplicar".